apiVersion: v1
kind: Namespace
metadata:
  name: longhorn
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate
  namespace: longhorn
spec:
  secretName: certificate-secret
  dnsNames:
  - "longhorn.domainname.com"
  issuerRef:
    name: clusterissuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate
spec:
  secretName: certificate-secret
  dnsNames:
  - "demo.domainname.com"
  issuerRef:
    name: clusterissuer
    kind: ClusterIssuer
    group: cert-manager.io